name: libnpengine builder
run-name: Build ${{ github.ref_name }}

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'libnpengine-*'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: >
          boost-dev
          make
          cmake
          clang
          flex-dev
          git
          bison
          doas

    - name: build libnpa
      run: |
        git clone https://github.com/Madagambada/libnpa.git -b libnpa-0.5.3
        cd libnpa
        echo "::group::Configure"
        mkdir build
        cd build
        export CXX=clang++
        export CC=clang
        cmake -DCMAKE_BUILD_TYPE=Release ..
        echo "::endgroup::"
        echo "::group::Build"
        make -j4
        echo "::endgroup::"
        doas make install
      shell: alpine.sh {0}

    - name: build libnpengine
      run: |
        echo "::group::Configure"
        mkdir build
        cd build
        export CXX=clang++
        export CC=clang
        cmake -DCMAKE_BUILD_TYPE=Release ..
        echo "::endgroup::"
        echo "::group::Build"
        make -j4
        echo "::endgroup::"
        cpack
      shell: alpine.sh {0}